# Generated by Django 2.2.7 on 2019-11-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('confirmar_senha', models.CharField(max_length=255)),
            ],
        ),
    ]
