# Generated by Django 2.2.7 on 2019-11-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='senha',
            new_name='password',
        ),
    ]
