# Generated by Django 2.2.7 on 2019-11-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_auto_20191106_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='numero_casa',
            new_name='numero',
        ),
    ]
